CREATE TABLE IF NOT EXISTS games (
    game_id                 CHAR(36)                                        NOT NULL,
    title                   VARCHAR(256)                                    NOT NULL,
    platform                VARCHAR(256)                                    NOT NULL,
    release_date            DATE,
    early_access            BOOLEAN                                         DEFAULT FALSE,
    release_region          ENUM('AS','BR','DE','EU','FR','JP','KO','NA')   NOT NULL,
    publisher               VARCHAR(256)                                    NOT NULL,
    developer               VARCHAR(256)                                    NOT NULL,
    franchise               VARCHAR(256)                                    DEFAULT '',
    genre                   VARCHAR(256)                                    NOT NULL,
    vr                      BOOLEAN                                         NOT NULL,
    dlc                     BOOLEAN                                         NOT NULL,
    english                 INT,
    owned                   BOOLEAN                                         DEFAULT false,
    owned_condition         VARCHAR(256)                                    DEFAULT '',
    date_purchased          DATE,
    purchase_price          DECIMAL,
    purchase_format         ENUM('digital', 'physical', 'both'),
    completed               BOOLEAN                                         DEFAULT false,
    date_completed          DATE,
    completion_time_hours   DECIMAL,
    rating                  DECIMAL,
    metacritic_rating       DECIMAL,
    gamefaqs_user_rating    DECIMAL,
    notes                   VARCHAR(256)                                    DEFAULT '',
    priority                INT,
    wishlisted              BOOLEAN                                         DEFAULT false,
    estimated_time_hours    DECIMAL,
    playing_status          INT                                             DEFAULT 0,
    release_year            YEAR                                            NOT NULL,
    PRIMARY KEY (game_id)
);
