name: games-master
services:
  db:
    image: postgres
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  backend:
    build:
      context: ./game_manager
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./game_manager:/code
    ports:
      - "9000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:8000/healthz || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    networks:
      - backend
  next-app:
    container_name: next-app
    build:
      context: ./game_frontend/with-docker-compose-app/next-app
      dockerfile: dev.Dockerfile

    # Set envrionment variables based on the .env file
    env_file:
      - ./game_frontend/with-docker-compose-app/.env
    volumes:
      - ./game_frontend/with-docker-compose-app/next-app/src:/app/src
      - ./game_frontend/with-docker-compose-app/next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
volumes:
  database_volume:
networks:
  backend:
  frontend: