version: '2.17'
services:
  mysql:
    image: mysql:latest
    restart: always
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      # - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      # - ./db/02_testdata.sql:/docker-entrypoint-initdb.d/02_testdata.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
  # Development only.   
  adminer:
    image: adminer
    restart: always
    ports:
      - ${DB_ADMINER_PORT}:8080
volumes:
  mysql_volume:
