PLATFORM_NAMES = {
    '3do': [],
    'acorn electron': [],
    'amstrad cpc': ['cpc'],
    'android': [],
    'apple ii': [],
    'arcade': ['arc', 'arcade games'],
    'atari 2600': ['2600'],
    'atari 7800': ['7800'],
    'atari 8-bit': [],
    'atari jaguar': ['jaguar'],
    'atari lynx': ['lynx'],
    'atari st': ['ast', 'st'],
    'bbc micro': ['bbc'],
    'bs-x': ['satellaview', 'snes', 'super nintendo', 'super nintendo entertainment system', 'super famicom', 'sfc'],
    'browser': ['web browser', 'online/browser', 'webonly'],
    'colecovision': [],
    'commodore 64': ['c64'],
    'commodore amiga': ['amiga', 'ami'],
    'commodore amiga cd32': ['amiga cd32', 'cd32', 'amiga', 'ami'],
    'commodore vic-20': ['vic-20', 'vic20'],
    'dsiware': ['nintendo dsi', 'dsi', 'ds', 'nintendo ds'],
    'dedicated console': ['television game', 'dedicated'],
    'epoch super cassette vision': ['super cassette vision'],
    'fm towns': [],
    'fm-7': ['fujitsu fm-7'],
    'famicom disk system': ['fds'],
    'game boy': ['nintendo game boy', 'gb'],
    'game boy advance': ['nintendo game boy advance', 'gba'],
    'game boy color': ['nintendo game boy color', 'gbc'],
    'game.com': ['tiger game.com'],
    'gamepark 32': ['gp32'],
    'google stadia': ['stadia'],
    'intellivision': [],
    'j2me': ['mobile', 'mobi'],
    'msx': [],
    'msx2': ['msx'],
    'mac os': ['macintosh', 'mac'],
    'n-gage': ['ngage'],
    'n-gage 2.0': ['n-gage', 'ngage'],
    'nec pc-8801': ['pc-8801', 'pc', 'pc88', 'pc-88', 'nec pc88', 'nec pc-88'],
    'nec pc-9801': ['pc-9801', 'pc', 'pc98', 'pc-98', 'nec pc98', 'nec pc-98'],
    'nes': ['famicom', 'nintendo entertainment system'],
    'neo-geo': ['neogeo', 'neo geo', 'neo', 'ng'],
    'neo-geo cd': ['neogeo', 'neo geo' 'neogeo cd', 'ncd', 'ngcd'],
    'neo-geo pocket': ['ngp', 'neogeo pocket', 'neo geo pocket'],
    'neo-geo pocket color': ['ngpc', 'neogeo pocket color', 'neo geo pocket color'],
    'new nintendo 3ds': ['nintendo 3ds', '3ds'],
    'nintendo 3ds': ['3ds', 'nintendo 3ds eshop', '3dse'],
    'nintendo 64': ['n64'],
    'nintendo 64dd': ['64dd', 'n64dd'],
    'nintendo ds': ['nds', 'ds'],
    'nintendo dsi': ['dsi'],
    'nintendo gamecube': ['gcn', 'gamecube', 'gc'],
    'nintendo pokémon mini': ['pokemon mini', 'pokémon mini', 'nintendo pokemon mini', 'pmini'],
    'nintendo switch': ['switch', 'ns'],
    'nintendo wii': ['wii', 'wii shop'],
    'nintendo wii u': ['wii u', 'wiiu', 'wii u eshop', 'nintendo wii u eshop'],
    'oculus quest': ['oq'],
    'ouya': [],
    'pc': ['windows pc', 'windows', 'dos', 'pc (microsoft windows)'],
    'pc-fx': ['pcfx'],
    'pdp-10': ['pdp10', 'pc'],
    'philips cd-i': ['cdi', 'cd-i'],
    'pioneer laseractive': ['laseractive'],
    'playstation': ['psx', 'ps1', 'sony playstation', 'ps'],
    'playstation 2': ['ps2', 'sony playstation 2'],
    'playstation 3': ['ps3', 'sony playstation 3'],
    'playstation 4': ['ps4', 'sony playstation 4'],
    'playstation 5': ['ps5', 'sony playstation 5'],
    'playstation network': ['psn'],
    'playstation portable': ['psp'],
    'playstation vita': ['psvita', 'vita'],
    'playdate': [],
    'snes': ['super famicom', 'super nintendo entertainment system', 'sfc'],
    'sega 32x': ['32x'],
    'sega cd': ['scd'],
    'sega dreamcast': ['dreamcast', 'dcast', 'dc'],
    'sega game gear': ['gg', 'game gear', 'gamegear', 'sega gamegear'],
    'sega genesis': ['genesis', 'mega drive', 'sega mega drive', 'gen', 'md'],
    'sega master system': ['sms', 'master system'],
    'sega sg-1000': ['sg-1000', 'sg1000', 'sega sg1000'],
    'sega saturn': ['saturn', 'sat'],
    'sharp x1': ['x1'],
    'sharp x68000': ['x68000', 'x68k', 'sharp x68k'],
    'turbografx-16': ['tg16', 'turbografx16', 'pce' 'pc engine'],
    'turbografx-cd': ['tcd', 'turbo cd', 'turbo-cd', 'turbografxcd', 'pc engine cd-rom', 'pc engine cd-rom²'],
    'vectrex': [],
    'virtual boy': ['vb'],
    'watara supervision': ['supervision'],
    'wiiware': ['wii', 'nintendo wii', 'wii shop'],
    'wonderswan': ['ws', 'bandai wonderswan'],
    'wonderswan color': ['wsc', 'bandai wonderswan color'],
    'xbox': ['xb', 'microsoft xbox'],
    'xbox 360': ['360', 'x360', 'microsoft xbox 360', 'xbla', 'xbox live arcade', 'xblig', 'xbox live indie games'],
    'xbox one': ['xone', 'microsoft xbox one'],
    'xbox series x|s': ['xbox series', 'xbox series x/s' 'xbsx', 'xbox series x', 'xbox series s'],
    'zx spectrum': ['spectrum', 'zx', 'sinclair zx81/spectrum', 'sinclair zx spectrum'],
    'zeebo': [],
    'ios': ['iphone', 'iphn', 'ipad', 'ios (iphone/ipad)']
}