"""Constants for the ExcelParser project"""

PLATFORM_NAMES = {
    "3do": ["3do interactive multiplayer"],
    "acorn archimedes": ["archimedes", "arch", "acorn 32-bit"],
    "acorn electron": ["electron"],
    "action max": ["am", "actionmax"],
    "amstrad cpc": ["cpc"],
    "android": ["and"],
    "apple ii": ["apple iigs", "apl2"],
    "arcade": ["arc", "arcade games", "hyper neo geo 64"],
    "atari 2600": ["2600"],
    "atari 5200": ["5200"],
    "atari 7800": ["7800"],
    "atari 8-bit": ["atari xe", "atari 400/800", "a800"],
    "atari jaguar": ["jaguar", "jag", "atari jaguar cd", "jaguar cd"],
    "atari jaguar cd": ["atari jaguar cd", "jaguar cd", "jcd"],
    "atari lynx": ["lynx"],
    "atari st": ["ast", "st"],
    "bbc micro": ["bbc", "bbc microcomputer system"],
    "brew": ["mobile", "mobi", "legacy mobile device", "mob"],
    "bs-x": [
        "satellaview",
        "snes",
        "super nintendo",
        "super nintendo entertainment system",
        "super famicom",
        "sfc",
        "super nintendo (snes)",
    ],
    "browser": ["web browser", "online/browser", "webonly", "fla", "flash", "web"],
    "colecovision": ["cvis"],
    "commodore 64": ["c64", "commodore c64/128/max"],
    "commodore amiga": ["amiga", "ami"],
    "commodore amiga cd32": ["amiga cd32", "cd32", "amiga", "ami"],
    "commodore plus/4": ["c-plus-4", "cp4", "commodore p4", "commodore 16, plus/4"],
    "commodore vic-20": ["vic-20", "vic20", "vc20"],
    "dsiware": ["nintendo dsi", "dsi", "ds", "nintendo ds", "dsiw"],
    "dedicated console": [
        "television game",
        "dedicated",
        "plug & play",
        "plug and play",
        "ded",
    ],
    "epoch super cassette vision": ["super cassette vision", "scv"],
    "fm towns": ["fmt", "fm towns marty"],
    "fm-7": ["fujitsu fm-7", "fujitsu micro 7", "micro 7", "fm7"],
    "famicom disk system": ["fds", "family computer disk system", "nes"],
    "game boy": ["nintendo game boy", "gb", "gameboy"],
    "game boy advance": [
        "nintendo game boy advance",
        "gba",
        "gameboy advance",
        "gameboy advance video",
    ],
    "game boy color": ["nintendo game boy color", "gbc", "gameboy color"],
    "game.com": ["tiger game.com", "gcomd"],
    "gamepark 32": ["gp32"],
    "gizmondo": ["giz"],
    "google stadia": ["stadia", "sta"],
    "intellivision": ["intv"],
    "j2me": ["mobile", "mobi", "legacy mobile device", "mob"],
    "msx": [],
    "msx turbo r": ["msx"],
    "msx2": ["msx"],
    "mac os": ["macintosh", "mac"],
    "n-gage": ["ngage", "nge"],
    "n-gage 2.0": ["n-gage", "ngage", "n-gage (service)", "nge"],
    "nec pc-6001": [
        "pc-6001",
        "pc",
        "pc6001",
        "pc60",
        "pc-60",
        "nec pc60",
        "nec pc-60",
        "nec pc6001",
        "nec pc-6001",
        "6001",
        "pc-6000 series",
    ],
    "nec pc-8801": [
        "pc-8801",
        "pc",
        "pc88",
        "pc-88",
        "nec pc88",
        "nec pc-88",
        "pc-8800 series",
    ],
    "nec pc-9801": [
        "pc-9801",
        "pc",
        "pc98",
        "pc-98",
        "nec pc98",
        "nec pc-98",
        "pc-9800 series",
    ],
    "nes": [
        "famicom",
        "nintendo entertainment system",
        "family computer",
        "nintendo",
        "nintendo (nes)",
    ],
    "neo-geo": ["neogeo", "neo geo", "neo", "ng", "neo geo aes", "neo geo mvs"],
    "neo-geo cd": [
        "neogeo",
        "neo geo",
        "neogeo cd",
        "ncd",
        "ngcd",
        "neo geo cd",
    ],
    "neo-geo pocket": ["ngp", "neogeo pocket", "neo geo pocket"],
    "neo-geo pocket color": ["ngpc", "neogeo pocket color", "neo geo pocket color"],
    "new nintendo 3ds": ["nintendo 3ds", "3ds", "nintendo 3ds eshop"],
    "nintendo 3ds": ["3ds", "nintendo 3ds eshop", "3dse"],
    "nintendo 64": ["n64"],
    "nintendo 64dd": ["64dd", "n64dd", "n64d"],
    "nintendo ds": ["nds", "ds"],
    "nintendo dsi": ["dsi", "nds", "ds"],
    "nintendo gamecube": ["gcn", "gamecube", "gc", "gcube"],
    "nintendo pokémon mini": [
        "pokemon mini",
        "pokémon mini",
        "nintendo pokemon mini",
        "pmini",
        "pmm",
    ],
    "nintendo switch": ["switch", "ns"],
    "nintendo wii": ["wii", "wii shop"],
    "nintendo wii u": ["wii u", "wiiu", "wii u eshop", "nintendo wii u eshop"],
    "oculus quest": ["oq", "oculus vr", "quest", "meta quest", "mq"],
    "ouya": [],
    "pc": [
        "windows pc",
        "windows",
        "dos",
        "pc (microsoft windows)",
        "msdos",
        "ms-dos",
        "steamvr",
        "osx",
        "msd",
        "linux",
        "win",
    ],
    "pc-fx": ["pcfx"],
    "pdp-10": ["pdp10", "pc"],
    "philips cd-i": ["cdi", "cd-i"],
    "pioneer laseractive": ["laseractive", "la"],
    "playstation": [
        "psx",
        "ps1",
        "sony playstation",
        "ps",
        "playstation 1",
        "sony playstation 1",
    ],
    "playstation 2": ["ps2", "sony playstation 2"],
    "playstation 3": [
        "ps3",
        "sony playstation 3",
        "playstation network (ps3)",
    ],
    "playstation 4": ["ps4", "sony playstation 4", "playstation vr", "psvr"],
    "playstation 5": ["ps5", "sony playstation 5", "playstation vr2", "psvr2"],
    "playstation network": [
        "psn",
        "ps3",
        "sony playstation 3",
        "playstation 3",
        "playstation 4",
        "sony playstation 4",
        "playstation portable",
        "psp",
        "ps4",
        "sony playstation portable",
        "sony psp",
        "playstation vita",
        "psvita",
        "vita",
        "ps vita",
        "psv",
        "sony playstation vita",
        "sony ps vita",
        "playstation network (vita)",
        "playstation network (psp)",
        "playstation network (ps3)",
    ],
    "playstation portable": [
        "psp",
        "sony playstation portable",
        "sony psp",
        "playstation network (psp)",
    ],
    "playstation vita": [
        "psvita",
        "vita",
        "ps vita",
        "psv",
        "sony playstation vita",
        "sony ps vita",
        "playstation network (vita)",
    ],
    "playdate": ["pd"],
    "risc pc": ["acorn archimedes", "archimedes", "arch", "acorn 32-bit", "risc"],
    "snes": [
        "super famicom",
        "super nintendo entertainment system",
        "sfc",
        "super nintendo",
    ],
    "sega 32x": ["32x", "s32x"],
    "sega cd": ["scd"],
    "sega dreamcast": ["dreamcast", "dcast", "dc"],
    "sega game gear": ["gg", "game gear", "gamegear", "sega gamegear"],
    "sega genesis": [
        "genesis",
        "mega drive",
        "sega mega drive",
        "gen",
        "md",
        "sega mega drive/genesis",
    ],
    "sega master system": ["sms", "master system", "sega master system/mark iii", "ms"],
    "sega sg-1000": ["sg-1000", "sg1000", "sega sg1000", "sg1"],
    "sega saturn": ["saturn", "sat"],
    "sharp x1": ["x1"],
    "sharp x68000": ["x68000", "x68k", "sharp x68k", "x68"],
    "supergrafx": [
        "nec supergrafx",
        "sgfx",
        "sg",
        "turbografx-16",
        "tg16",
        "turbografx16",
        "pce",
        "pc engine",
        "pce engine supergrafx",
        "turbografx-16/pc engine cd",
        "turbografx-16/pc engine",
        "turbografx 16",
    ],
    "tapwave zodiac": ["zodiac", "zod"],
    "trs-80 color computer": [
        "trs-80",
        "trs-80 cc",
        "trs80",
        "color computer",
        "trs-80 color",
        "trs 80 color",
        "trs 80 color computer",
        "trs 80",
        "coco",
        "tandy color computer",
        "tandy coco",
        "trs-80 coco",
    ],
    "turbografx-16": [
        "tg16",
        "turbografx16",
        "pce",
        "pc engine",
        "pce engine supergrafx",
        "turbografx-16/pc engine cd",
        "turbografx-16/pc engine",
        "turbografx 16",
    ],
    "turbografx-cd": [
        "tcd",
        "turbo cd",
        "turbo-cd",
        "turbografxcd",
        "pc engine cd-rom",
        "pc engine cd-rom²",
        "turbografx 16 cd",
    ],
    "tvos": ["ios", "iphone", "iphn", "ipad", "ios (iphone/ipad)", "tos"],
    "vectrex": ["vecx"],
    "virtual boy": ["vb", "nintendo virtual boy", "nintendo vb"],
    "watara supervision": ["supervision", "watara/quickshot supervision", "sv"],
    "watchos": ["ios", "iphone", "iphn", "ipad", "ios (iphone/ipad)", "wos"],
    "wiiware": ["wii", "nintendo wii", "wii shop", "virtual console", "vc", "ww"],
    "wonderswan": ["ws", "bandai wonderswan"],
    "wonderswan color": ["wsc", "bandai wonderswan color"],
    "xbox": ["xb", "microsoft xbox"],
    "xbox 360": [
        "360",
        "x360",
        "microsoft xbox 360",
        "xbla",
        "xbox live arcade",
        "xblig",
        "xbox live indie games",
        "xbl",
        "xbox 360 games store",
    ],
    "xbox one": ["xone", "microsoft xbox one"],
    "xbox series x|s": [
        "microsoft xbox series x",
        "xbox series",
        "xbox series x/s",
        "xbsx",
        "xbox series x",
        "xbox series s",
        "xs",
    ],
    "zx spectrum": ["spectrum", "zx", "sinclair zx81/spectrum", "sinclair zx spectrum"],
    "zeebo": ["zb"],
    "ios": ["iphone", "iphn", "ipad", "ios (iphone/ipad)"],
}
